### ISSUE TITLE
[BUG] After successful connection and redirect : NoSuchMethodError => BrokeredIdentityContext

### ISSUE THREAD

**Issue by quentin-lalitte** [InseeFr/Keycloak-FranceConnect#129]
When you're redirected after a successful connection, I got the follow error on my keycloak server : 

> Uncaught server error: java.lang.NoSuchMethodError: 'void org.keycloak.broker.provider.BrokeredIdentityContext.<init>(java.lang.String, org.keycloak.models.IdentityProviderModel)'

This happen when I upgrade to the latest version 7.0.0

It works fine on 6.5.0

Those changes could be the cause 

![Image](https://github.com/user-attachments/assets/e40231b4-19b3-46f6-961d-4988484f9fa7)

I'm running Keycloak 24.0.4

**Comment by clement-dufaure** [comment]
Hi, [the version 7.0.0 of this plugin is compatible with Keycloak 25.0.0 and higher](https://github.com/InseeFr/Keycloak-FranceConnect/blob/master/README.en.md#compatibility), Compatibility with Keycloak 25+ is the purpose of the release 7.0.0 : https://github.com/InseeFr/Keycloak-FranceConnect/releases/tag/7.0.0
